#!/bin/bash

if [[ $# -eq 1 ]]
then
	if [ $1 = "-h" ] || [ $1 = "--help" ]
	then
		echo "Use -input=input_file to give input java file to the parser."
		echo "Use -out=output_file to give name of output dot file."
	else
		echo "Error: use -h or --help"
		exit 1
	fi
elif [[ $# -eq 2 ]]
then
	arg1=`echo $1 | cut -d "=" -f1`
	arg2=`echo $1 | cut -d "=" -f2`
	arg3=`echo $2 | cut -d "=" -f1`
	arg4=`echo $2 | cut -d "=" -f2`
	if [ $arg2 = "" ] || [ $arg4 = "" ]
	then
		echo "Error: use -h or --help"
		exit 1
	fi
	input_file=""
	output_file=""
	if [[ $arg1 = "-input" ]]
	then
		input_file=$arg2
		if [[ $arg3 = "-out" ]]
		then
			output_file=$arg4
		else
			echo "Error: use -h or --help"
			exit 1
		fi

	elif [[ $arg1 = "-out" ]]
	then
		output_file=$arg2
		if [[ $arg3 = "-input" ]]
		then
			input_file=$arg4
		else
			echo "Error: use -h or --help"
			exit 1
		fi
	else
		echo "Error: use -h or --help"
		exit 1
	fi
	make
	./parser < $input_file > $output_file
	if [[ $? -ne 0 ]]
	then
		exit 1
	fi
	dot -Tps $output_file -o graph.ps
else
	echo "Error: use -h or --help"
	exit 1
fi

# make
# ./parser < $1 > tp.dot
# dot -Tps tp.dot -o tp.ps
# xdg-open tp.ps
# rm graph.dot
